In [5]:
%matplotlib inline
import numpy as np
from scipy import linalg

In [5]:
# Task 6.1
A = np.array([[1,2,3], [4, 0, 6], [7, 8, 9]])
B = np.array([12,2,1])
np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])

In [6]:
# Task 6.2
A = np.array([[1,2,-1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15 ])
np.linalg.lstsq(A,B)

<ipython-input-6-6507f5b3ff3c>:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A,B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [34]:
# Task 6.3
A = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 27, 42]])
C = np.concatenate((A,B.T), axis=1)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)
B = np.array([12, 27, 42])
np.linalg.solve(A,B)

array([-14.,  31., -12.])

In [7]:
#Task 6.4
A = np.array([[1,2,3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print (P)
print (L)
print (U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [9]:
# Task 6.5
A = np.array([[1,2,-1], [8, -5, 2]])
B = np.array ([1,12])
np.linalg.lstsq (A,B)

<ipython-input-9-7ddb77425f8f>:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq (A,B)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

In [11]:
# Task 6.6
A = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
B = np.array ([2,5,11])
Q, R = np.linalg.qr(A)
print (A)
print (Q)
print (R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


array([1.50000000e+00, 9.45096256e-15])

In [13]:
R1 = R[:2,:2]
R1


array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [14]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.54871729e-15])

In [15]:
X1 = np.linalg.solve(R1,B1)
X1

array([1.50000000e+00, 9.45096256e-15])